### ISSUE TITLE
add skeleton function to setup a new WPS bird ...

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/babybird#1]

**Comment by cehbrecht** [comment]
examples for "skeletons":
- http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/project.html#project-narr
- http://conda.pydata.org/docs/commands/build/conda-skeleton.html

**Comment by huard** [comment]
https://cookiecutter.readthedocs.io/en/latest/readme.html#readme

**Comment by cehbrecht** [comment]
we have a cookiecutter now: https://github.com/bird-house/cookiecutter-birdhouse 

Babybird goes to sleep ...
